### ISSUE TITLE
Non-replicable loops with sequential backend

### ISSUE THREAD

**Issue by brentonk** [renozao/doRNG#1]
The first time I call `doRNG` when a sequential backend is registered, the output differs from all subsequent calls. But then all of the subsequent calls yield the same output, assuming the seed is set the same.

Example script:

``` r
library("doRNG")
library("doMC")
library("foreach")

registerDoSEQ()

registerDoRNG(123)
res1 <- foreach (i = 1:10) %dorng% { runif(1) }
registerDoRNG(123)
res2 <- foreach (i = 1:10) %dorng% { runif(1) }

print(identical(res1, res2))            # FALSE

registerDoRNG(123)
res3 <- foreach (i = 1:10) %dorng% { runif(1) }

print(identical(res2, res3))            # TRUE
```

My session info:

```
R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin13.3.0 (64-bit)

locale:
[1] en_US/en_US/en_US/C/en_US/en_US

attached base packages:
[1] parallel  methods   stats     graphics  grDevices utils     datasets 
[8] base     

other attached packages:
[1] doMC_1.3.3      iterators_1.0.7 doRNG_1.6       rngtools_1.2.4 
[5] pkgmaker_0.22   registry_0.2    foreach_1.4.2  

loaded via a namespace (and not attached):
[1] codetools_0.2-8 compiler_3.1.1  digest_0.6.4    stringr_0.6.2  
[5] tools_3.1.1     xtable_1.7-3   
```

I can cheaply "fix" the problem by preceding my code with `registerDoRNG(); invisible(foreach(i = 1) %dorng% NULL)`, but I'd rather not resort to that.

**Comment by HenrikBengtsson** [comment]
I just bumped into this issue using doRNG 1.6 installed from CRAN.  Installing doRNG 1.6.2 on the develop branch fixed it.  Since this is quite an old issue, may I suggest to submit a new version to CRAN?

**Comment by renozao** [comment]
Indeed. Will try do that soon.
