### ISSUE TITLE
CRAN package formally orphaned

### ISSUE THREAD

**Issue by fweber144** [renozao/doRNG#23]
It seems like the CRAN package has been updated by the CRAN team to v1.8.3, with the updated `NEWS` file saying:

```
*************************************************************************
Changes in version 1.8.3 by CRAN Team
*************************************************************************

Removed dependence on abandoned packae 'pkgmaker', including removing vignette.

Package has been formally orphaned (it was last touched in Jan 2020
and the 'maintainer' is unresponsive).
```

I'm not sure whether this means that the package might get archived soon. In any case, I thought it might be better to let you know (especially because there was #16 in the past and it seems like you took some action back then). It would be great to keep doRNG on CRAN. It's a package I use a lot, thanks for developing it.

**Comment by christopherkenny** [comment]
Thanks @renozao for your maintenance of doRNG thus far. Based on an email (below) from Brian Ripley, it appears that the package needs a maintainer by January 19, 2023. 

> Packages
> 
> ADAPTS BSL Counterfactual EMAS EPX EnsembleBase EnsembleCV
EnsemblePCReg EnsemblePenReg IFAA KarsTS LongDat MERO Mediana
MedianaDesigner NADIA ORdensity PRSPGx RapidoPGS Rnmr1D
RobGARCHBoot Robyn SGP SparseMDC TRexSelector WebGestaltR
adjustedCurves autoMrP bartMachine bestNormalize bhmbasket
bigsnpr cbl deltaccd ellipticalsymmetry envi ewoc exuber fect
funGp gbts gratis gsynth highMLR hwep hybridModels imp4p
kernelshap latentcor lcc locStra longit markovMSM metaplus mi4p
midasml missCompare missForest mixedCCA momentuHMM mplot
obliqueRSF promor randomLCA redist robmixglm robust2sls scMappR
scpi seqimpute simputation skpr sparrpowR speaq survidm updog
varclust
> 
> require package doRNG directly or indirectly and it has now been
orphaned (the 'maintainer' having failed to responds several times over
months).
> 
> So the CRAN policy
> 
> "Orphaned CRAN packages should not be strict requirements (in the
‘Depends’, ‘Imports’ or ‘LinkingTo’ fields, including indirectly).
They are allowed in ‘Suggests’ if used conditionally, although this is
discouraged."
>
> now applies. Please adjust your packages to comply by 2023-01-19.
>
> If one of you wants to take over as maintainer please do so (but do not
discuss this on the CRAN list -- we have quite enough to read).

**Comment by privefl** [comment]
I guess all the packages depending on this one will get removed from CRAN by then, right?

**Comment by renozao** [comment]
My intention is to bring back pkgmaker up to CRAN on time so that doRNG and other packages can still happily live together on CRAN.

**Comment by privefl** [comment]
Fantastic!
Thanks

**Comment by christopherkenny** [comment]
Wonderful, @renozao. Thank you.

**Comment by HenrikBengtsson** [comment]
> I guess all the packages depending on this one will get removed from CRAN by then, right?

FWIW, if so, I think it's only hard dependencies that are affected.  At least in the first round.  

For example, **[doFuture](https://cran.r-project.org/web/packages/doFuture/index.html)** depends on **doRNG** optionally via `Suggests:` and I did not get a notification, **doFuture** is not mentioned in the above CRAN email.  The current orphaned state triggers a:

```
Check: package dependencies
Result: NOTE
    Suggests orphaned package: ‘doRNG’ 
```

e.g. <https://cran.r-project.org/web/checks/check_results_doFuture.html>.

**Comment by RobinDenz1** [comment]
@renozao Do you perhaps have any updates on this? I do like the doRNG package a lot and would love to keep using it in my package, but if the "orphaned issue" is not fixed until the 18th of January I will be forced to stop using it. Otherwise, CRAN will remove my package as well.

**Comment by renozao** [comment]
Hi all,
I have submitted a new version of `pkgmaker` to CRAN just now.
It is all green on my side: https://github.com/renozao/pkgmaker/actions/runs/3876288108

**Comment by HenrikBengtsson** [comment]
> I have submitted a new version of pkgmaker to CRAN just now.

Great!

Maybe you already know, but I think you're also gonna have to resubmit **doRNG** to reclaim ownership and take it out of the ORPHANED state.

**Comment by renozao** [comment]
Thanks for pointing this out @HenrikBengtsson .
Will prepare a submission for doRNG then, to have ready when pkgmaker makes it back to CRAN.

**Comment by renozao** [comment]
Update: `pkgmaker` is back on CRAN and I submitted an update for doRNG just now. Awaiting for checks.

Side question: @HenrikBengtsson would you know how to setup r-lib github-actions correctly for Mac OS and Windows so that package `doMPI` gets installed properly? I tried a couple ways with `pacman` and `homebrew` without success.
I thought that you may have experience on that for `future` and `doFuture`.
Thanks!

**Comment by HenrikBengtsson** [comment]
That's good news

> Side question: @HenrikBengtsson would you know how to setup r-lib github-actions correctly for Mac OS and Windows so that package `doMPI` gets installed properly? I tried a couple ways with `pacman` and `homebrew` without success.
> I thought that you may have experience on that for `future` and `doFuture`.

Sorry, I don't.  I don't have access to macOS, and haven't tried on MS Windows, but I know the underlying **Rmpi** is a pain to install on Linux.  It does _not_ install out of the box on Linux, and honestly, I don't know why it's not configured to do so (or at least so you only have to specify which MPI type to use - now you have to specify paths too).  Linux instruction can be found at https://www.c4.ucsf.edu/howto/r.html#the-rmpi-package.  Maybe something similar can be done for macOS?(!?)

**Comment by renozao** [comment]
Thanks @HenrikBengtsson.
I managed to get the macOS check to work. I used:
```
- name: MacOS binary dependencies
        if: matrix.config.os == 'macos-latest'
        run: |
          brew install gcc
          brew install open-mpi
          brew install texlive
```

Installation on Linux is not too bad, since it is clearly stated which apt package to install. 
Only missing piece is Windows. Leaving it for later.

See: https://github.com/renozao/doRNG/actions/runs/3911749007/jobs/6685493826

**Comment by HenrikBengtsson** [comment]
> Installation on Linux is not too bad, since it is clearly stated which apt package to install.

I just tried on Ubuntu 20.04, and there **Rmpi** does indeed install out of the box, so I guess it's just RedHat/CentOS one has to go an extra mile.

**Comment by renozao** [comment]
Update on this issue: a new version of doRNG is now on CRAN (version 1.8.6).
I believe this solves the orphaned dependency issue and you should not have to do anything on your side.
Thank you!

**Comment by renozao** [comment]
@HenrikBengtsson would you know of an easy way to contact all the maintainers that received the email about doRNG being orphaned?

**Comment by HenrikBengtsson** [comment]
> @HenrikBengtsson would you know of an easy way to contact all the maintainers that received the email about doRNG being orphaned?

Sorry, I don't. But, I think the Tidyverse folks reach out to revdep maintainers once in a while.  Maybe there's something in **devtools** or **revdepcheck**.

**Comment by idblr** [comment]
@renozao [email me](mailto:ian.buller@alumni.emory.edu) and I can forward you the list CRAN sent to maintainers
