### ISSUE TITLE
README: "The development project is hosted on R-forge"

### ISSUE THREAD

**Issue by HenrikBengtsson** [renozao/doRNG#4]
The README.md file still mentions R-forge;

> The development project is hosted on R-forge at http://r-forge.r-project.org/projects/dorng/

Is that true?

**Comment by renozao** [comment]
I must admit I haven't updated my R-forge repos in a while. 
I have been asking the R-forge admins to re-enable external repos support so that I could point to github, but I believe this is still pending. I need to clean this up.

So definitely use code from github if needed.
