### ISSUE TITLE
Submit doRNG 1.6.2 to CRAN

### ISSUE THREAD

**Issue by HenrikBengtsson** [renozao/doRNG#5]
A kind reminder to submit doRNG 1.6.2 to CRAN, cf. Issue #1.

**Comment by noamross** [comment]
Another vote for this!

**Comment by twolodzko** [comment]
By the way, doRNG is not available on Windows on CRAN -- will it be resolved in the 1.6.2 version?

**Comment by renozao** [comment]
An updated source version is on CRAN now. The binaries should follow once built.
I think the windows version was not shipping because of unit tests that used MPI. I disabled those now, because I was also having issues with Rmpi clusters.
