### ISSUE TITLE
set.seed equivalent for doRNG loop iteration

### ISSUE THREAD

**Issue by fintzij** [renozao/doRNG#6]
Hello,

Is there a way to obtain the seed that is used in a given iteration of a doRNG loop? I am trying to debug some code and need the seed in order to replicate the problem. 

To be precise, I am looking to take the output of attr(res, 'rng'), which is a series of integers of length seven, and use that in set.seed(). 

Thank you!
Jon

(Apologies in advance if my question reflects my ignorance.)

**Comment by renozao** [comment]
You can use `rngtools` functions for this:

```R
# setup doRNG
library(doRNG)
registerDoRNG()
# run loop
res <- foreach(1:4, .combine = 'c') %dopar% { runif(1) }

# you can extract the RNG seed list using getRNG on the result object
identical(getRNG(res), attr(res, 'rng'))

# then you can set the RNG using the seed of a particular iteration using setRNG
# and run the code of that iteration
setRNG(getRNG(res)[[3L]])
res_iteration3 <- runif(1)
identical(res_iteration3, res[[3L]])
```

Depending on your environment, you may want to call those function using explicit prefix `rngtools::` because some other packages may define functions with the same name.

**Comment by fintzij** [comment]
Thank you!
